### ISSUE TITLE
Loss of final newline

### ISSUE THREAD

**Issue by mastertinner** [yory8/clipman#43] opened 2020-05-06 17:30 UTC
I've been using clipman on my Arch system and love it. However, there's a problem with NeoVim:

I have `set clipboard=unnamedplus` set in my `init.vim` file to integrate it with the system clipboard. When I copy a line in NeoVim (e.g. with `yy`) and then want to paste it (with `p`), it pastes it not to the next line but rather into the line where I am. So the default Vim/NeoVim behavior is changed in a way that makes it unusable.

I'm using NeoVim v0.4.3, Clipman v1.5.0, wl-clipboard v2.0.0, bemenu v0.3.0 and initialize Clipman with the following lines in my Sway config:

```txt
exec wl-paste --type text --watch clipman store
bindsym $mod+v exec clipman pick --tool bemenu
```

If I remove these lines from the Sway config, everything works as expected in NeoVim.

**Comment by yory8** [comment] 2020-05-07 08:40
I can confirm this. It happens when we receive stdin from wl-paste: go's scanner drops the last newline. I'll investigate a solution soon.

**Comment by mastertinner** [comment] 2020-05-07 09:12
Great. Thanks, @yory8!

**Comment by yory8** [comment] 2020-05-07 15:36
Fixed in master. I'll cut a new release very soon if it works without creating new issues.

**Comment by sentriz** [comment] 2020-05-07 15:38
master fixed this for me :) thanks!

**Comment by sentriz** [comment] 2020-06-29 17:29
update: seems to be fixed for line-wise yanks like above, but visual block yanks seems to be affected too

here is a video: https://streamable.com/rfsi49

that process on the bottom pane is `wl-paste --type text --watch clipman store --max-items 500 --unix` (unix flag doesnt seems to make a different with this issue)

if anyone doesn't know vim to try reproduce, i'm doing 

<kbd>Ctrl-v</kbd> to enter visual block mode, hjkl keys to move around, <kbd>y</kbd> to yank the block, and then <kbd>p</kbd> to put

**Comment by yory8** [comment] 2020-06-29 20:58
Can confirm. But I don't think we can fix it. I fear that any clipboard manager would break in this case. Will investigate further tomorrow.

**Comment by yory8** [comment] 2020-06-29 21:02
Workaround: run clipman store with `-P` enabled. It's caused by the persist option. Unfortunately there's no way to make them play well together.

**Closed** 2020-06-29 21:08 UTC
Labels: bug

**Comment by sentriz** [comment] 2020-06-30 09:23
thank you!

**Comment by gandalf3** [comment] 2020-09-04 23:56
Would it be possible to not write to the clipboard immediately, but only when the process providing the current clipboard content exits? This seems to be how clipster/various X11 clipboard managers managed to avoid messing with vim etc.

**Comment by yory8** [comment] 2020-09-05 06:57
Impossible on wayland, by design. We don't know what other applications are doing.

Flawless persistence-after-exit on wayland can be provided only by the WM itself, but they decided to keep the X11 design (drop everything on exit).

**Comment by gandalf3** [comment] 2020-09-05 10:05
@yory8 It seems [there is such an event](https://github.com/swaywm/sway/issues/5480#issuecomment-687580846) (a NULL is passed to the selection callback), but this [seems to be ignored by wl-paste](https://github.com/bugaevc/wl-clipboard/blob/master/src/wl-paste.c#L185).

Perhaps instead of clipman being run as an argument to wl-paste, it could make use of the wayland clipboard API directly, and only write to the clipboard after a null event?

**Comment by yory8** [comment] 2020-09-05 21:03
@gandalf3 thanks for the links, TIL. I was remembering incorrectly. 

You are right that this can only be fixed by using the API directly. However, I don't know C, and bindings for other languages are incomplete, so it's unlikely that I'll ever manage to do it (I already attempted a rewrite in rust, but their wrapper is missing critical functionality).

**Comment by gandalf3** [comment] 2020-09-06 08:41
@yory8 I've created a pull request on wl-paste which adds an option to emit null characters on null events: https://github.com/bugaevc/wl-clipboard/pull/93

If it gets merged, would it be possible to adapt clipman to handle incoming nulls accordingly? Perhaps that would be the simpler than a total rewrite!

**Comment by yory8** [comment] 2020-09-07 06:29
Seems like I was remembering correctly, seeing bugaevc comment to your PR. 

I don't like emitting null, for the reasons already told by him. It's an ugly hack (just like our current implementation of persistence, which is full of problems, and in retrospect should have been opt-in rather than opt-out). This is something that should be addressed by wayland itself.

**Comment by yory8** [comment] 2020-09-07 07:26
To be clear, my point is that we can't fix a clipman hack by introducing a hack into another (much more important and fundamental) program. This specif problem of persistence-after-exit, if limited to text only, could be easily fixed inside clipman itself if we used wl-clipboard's library internals directly.

**Comment by gandalf3** [comment] 2020-09-07 08:47
Full of problems? AFAIK the only problem is that copy/pasting a solitary null character would no long be possible as it would be indistinguishable from clearing the clipboard (and it even then, it would be possible support via a workaround, if anyone even cares enough to bother. It's not something that works in X11 clipboard manager (clipster) either).

There are other issues that bugaevc would like to solve via protocol improvements, (atomicity, cleared vs lost) but I don't currently see how those protocol improvements could actually be exposed via `wl-paste --watch` in a way which all that much cleaner than `--print0` anyway. Without some kind of addition like `--print0` such protocol changes would only benefit clipboard managers which utilize wayland APIs directly.

**Comment by yory8** [comment] 2020-09-07 11:09
> full of problems
I mean the implementation of persistence in clipman (problems with vim visual block mode, with rich text, etc), which to be fair are problems entangled with our lack of support from non-text mimes.

Indeed copying literal null characters is probably something nobody has ever needed.

If bugaevc accepts your patch, I'll definitely use it here in clipman, I'm just skeptical that it's the correct way forward. 
The `--watch` option was introduced to help "naive" clipboard managers (ie that don't rely on the API directly) getting things done, but I remember since the beginning bugaevc was clear that it's just a workaround until someones writes a "proper" CM.
