### ISSUE TITLE
Emoji on clipboard breaks clipman 1.2.0

### ISSUE THREAD

**Issue by akvadrako** [yory8/clipman#36] opened 2020-02-10 09:52 UTC
Normally clipman works fine, but when copying emoji it crashes:

```
$ echo  📡 | clipman store -P --histpath='hist'
$ clipman pick --histpath='hist'
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  138 (RENDER)
  Minor opcode of failed request:  20 (RenderAddGlyphs)
  Serial number of failed request:  17
  Current serial number in output stream:  18
```

**Comment by yory8** [comment] 2020-02-11 08:59
Seems like you're using X rather than wayland (sway)? It works perfectly fine on wayland

**Comment by akvadrako** [comment] 2020-02-11 09:46
I am using sway. Indeed I don’t really understand the X message.

**Comment by yory8** [comment] 2020-02-11 16:23
This is very strange. I cannot reproduce it. 

- Could you try `clipman pick --histpath='hist' --tool=wofi` (you need wofi installed)? dmenu uses X, and is the only place from which an X error could come (though, I tried dmenu on my sistem and it works well).
- Also, does the error happen before opening dmenu or after you made your selection?

**Comment by akvadrako** [comment] 2020-02-11 16:49
Thanks, @yory8, wofi works. No menu is shown before the crash. Maybe it has to do with the dmenu version: I'm on 4.8.

**Comment by yory8** [comment] 2020-02-11 17:34
Doesn't seem to be 4.8: I tried both this and 4.9 and both work.
Anyway, I strongly recommend moving to wofi, as it's fully wayland based. Dmenu can be made wayland native only through a full rewrite, so it's destined to die off.

**Closed by yory8** 2020-02-11 17:34 UTC
Labels: more-information-needed
